/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CCDeliveryHeaderModule"
 * 	found in "CCDeliveryHeaderModule.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_CallIdentity_H_
#define	_CallIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallIdentity */
typedef struct CallIdentity {
	UTF8String_t	 main;
	UTF8String_t	*leg	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _CallIdentity_H_ */
