/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_AccessMethod_H_
#define	_AccessMethod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccessMethod__accessType_PR {
	AccessMethod__accessType_PR_NOTHING,	/* No components present */
	AccessMethod__accessType_PR_dialUp,
	AccessMethod__accessType_PR_dsl,
	AccessMethod__accessType_PR_lan,
	AccessMethod__accessType_PR_cable,
	AccessMethod__accessType_PR_wiFi,
	AccessMethod__accessType_PR_wiMax,
	AccessMethod__accessType_PR_other
} AccessMethod__accessType_PR;

/* AccessMethod */
typedef struct AccessMethod {
	struct AccessMethod__accessType {
		AccessMethod__accessType_PR present;
		union AccessMethod__accessType_u {
			NULL_t	 dialUp;
			NULL_t	 dsl;
			NULL_t	 lan;
			NULL_t	 cable;
			NULL_t	 wiFi;
			NULL_t	 wiMax;
			UTF8String_t	 other;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accessType;
	UTF8String_t	*accessEquipmentID	/* OPTIONAL */;
	NULL_t	*partOfMultipleLogin	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccessMethod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccessMethod;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessMethod_H_ */
