ASN_MODULE_SOURCES=	\
	/opencalea/T1.IAS/CmCC/IAS-CC-APDU.c	\
	/opencalea/T1.IAS/CmCC/CCDeliveryHeader.c	\
	/opencalea/T1.IAS/CmCC/PacketDirection.c	\
	/opencalea/T1.IAS/CmII/IAS-LAES-CmII-Abstract-Syntax-Module-OID.c	\
	/opencalea/T1.IAS/CmII/IasProtocol.c	\
	/opencalea/T1.IAS/CmII/IasMessage.c	\
	/opencalea/T1.IAS/CmII/Access-Attempt.c	\
	/opencalea/T1.IAS/CmII/Access-Accepted.c	\
	/opencalea/T1.IAS/CmII/Access-Failed.c	\
	/opencalea/T1.IAS/CmII/Access-Session-End.c	\
	/opencalea/T1.IAS/CmII/Access-Rejected.c	\
	/opencalea/T1.IAS/CmII/Access-Signaling-Message-Report.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Session-Start.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Session-Failed.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Session-End.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Session-Already-Established.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Header-Report.c	\
	/opencalea/T1.IAS/CmII/Packet-Data-Summary-Report.c	\
	/opencalea/T1.IAS/CmII/AccessMethod.c	\
	/opencalea/T1.IAS/CmII/IPAddress.c	\
	/opencalea/T1.IAS/CmII/AccessSessionID.c	\
	/opencalea/T1.IAS/CmII/AccessSessionCharacteristics.c	\
	/opencalea/T1.IAS/CmII/HeaderSet.c	\
	/opencalea/T1.IAS/CmII/InterceptedSignalingMessage.c	\
	/opencalea/T1.IAS/CmII/IAPSystemIdentity.c	\
	/opencalea/T1.IAS/CmII/IAS-CCDeliveryFormat.c	\
	/opencalea/T1.IAS/CmII/LEA-CmC-Delivery.c	\
	/opencalea/T1.IAS/CmII/MessageType.c	\
	/opencalea/T1.IAS/CmII/NetworkAccessNodeIdentity.c	\
	/opencalea/T1.IAS/CmII/PacketDataSessionID.c	\
	/opencalea/T1.IAS/CmII/PortNumber.c	\
	/opencalea/T1.IAS/CmII/ProtocolSignal.c	\
	/opencalea/T1.IAS/CmII/Protocol.c	\
	/opencalea/T1.IAS/CmII/ReasonForTermination.c	\
	/opencalea/T1.IAS/CmII/StreamSet.c	\
	/opencalea/T1.IAS/CmII/SubscriberIdentity.c	\
	/opencalea/T1.IAS/CmII/Value.c	\
	/opencalea/T1.IAS/CmII/TimeStamp.c	\
	/opencalea/T1.IAS/CmII/IAS-LAES-CmCC-Module-OID.c	\
	/opencalea/T1.IAS/CmII/CCAddress.c	\
	/opencalea/T1.IAS/CmII/DeliveryIdentifier.c	\
	/opencalea/T1.IAS/CmII/CaseIdentity.c	\
	/opencalea/T1.IAS/CmII/CCCIdentity.c	\
	/opencalea/T1.IAS/CmII/IpAddress.c	\
	/opencalea/T1.IAS/CmII/IPvalue.c	\
	/opencalea/T1.IAS/CmII/Location.c	\
	/opencalea/T1.IAS/CmII/CallIdentity.c	\
	/opencalea/T1.IAS/CmII/ContentIdentifier.c	\
	/opencalea/T1.IAS/CmII/CorrelationIdentifier.c

ASN_MODULE_HEADERS=	\
	IAS-CC-APDU.h	\
	CCDeliveryHeader.h	\
	PacketDirection.h	\
	IAS-LAES-CmII-Abstract-Syntax-Module-OID.h	\
	IasProtocol.h	\
	IasMessage.h	\
	Access-Attempt.h	\
	Access-Accepted.h	\
	Access-Failed.h	\
	Access-Session-End.h	\
	Access-Rejected.h	\
	Access-Signaling-Message-Report.h	\
	Packet-Data-Session-Start.h	\
	Packet-Data-Session-Failed.h	\
	Packet-Data-Session-End.h	\
	Packet-Data-Session-Already-Established.h	\
	Packet-Data-Header-Report.h	\
	Packet-Data-Summary-Report.h	\
	AccessMethod.h	\
	IPAddress.h	\
	AccessSessionID.h	\
	AccessSessionCharacteristics.h	\
	HeaderSet.h	\
	InterceptedSignalingMessage.h	\
	IAPSystemIdentity.h	\
	IAS-CCDeliveryFormat.h	\
	LEA-CmC-Delivery.h	\
	MessageType.h	\
	NetworkAccessNodeIdentity.h	\
	PacketDataSessionID.h	\
	PortNumber.h	\
	ProtocolSignal.h	\
	Protocol.h	\
	ReasonForTermination.h	\
	StreamSet.h	\
	SubscriberIdentity.h	\
	Value.h	\
	TimeStamp.h	\
	IAS-LAES-CmCC-Module-OID.h	\
	CCAddress.h	\
	DeliveryIdentifier.h	\
	CaseIdentity.h	\
	CCCIdentity.h	\
	IpAddress.h	\
	IPvalue.h	\
	Location.h	\
	CallIdentity.h	\
	ContentIdentifier.h	\
	CorrelationIdentifier.h

ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmCC/IAS-CC-APDU.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmCC/CCDeliveryHeader.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/UTF8String.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/BOOLEAN.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/BOOLEAN.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/INTEGER.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/NativeEnumerated.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/GeneralizedTime.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/GeneralizedTime.c
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/INTEGER.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/NULL.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/NULL.c
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/NativeEnumerated.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/NativeInteger.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/NativeInteger.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/NumericString.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/NumericString.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/OBJECT_IDENTIFIER.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/OBJECT_IDENTIFIER.c
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/UTF8String.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/VisibleString.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/VisibleString.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_SET_OF.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/asn_SET_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/constr_CHOICE.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/constr_CHOICE.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/constr_SEQUENCE.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/constr_SEQUENCE.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/constr_SET_OF.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/constr_SET_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_application.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_system.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_codecs.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_internal.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/OCTET_STRING.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/OCTET_STRING.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/BIT_STRING.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/BIT_STRING.c
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/asn_codecs_prim.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/asn_codecs_prim.h
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/ber_tlv_length.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/ber_tlv_length.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/ber_tlv_tag.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/ber_tlv_tag.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/ber_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/ber_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/der_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/der_encoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/constr_TYPE.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/constr_TYPE.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/constraints.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/constraints.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/xer_support.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/xer_support.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/xer_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/xer_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/xer_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/xer_encoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/per_support.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/per_support.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/per_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/per_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.IAS/CmII/per_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.IAS/CmII/per_encoder.c
ASN_CONVERTER_SOURCES+=main.c
ASN_CONVERTER_SOURCES+=routines.c
ASN_CONVERTER_SOURCES+=access_attempt.c
ASN_CONVERTER_SOURCES+=access_accepted.c
ASN_CONVERTER_SOURCES+=access_failed.c
ASN_CONVERTER_SOURCES+=access_session_end.c
ASN_CONVERTER_SOURCES+=access_rejected.c
ASN_CONVERTER_SOURCES+=access_signaling_message_report.c
ASN_CONVERTER_SOURCES+=packet_data_session_start.c
ASN_CONVERTER_SOURCES+=packet_data_session_end.c
ASN_CONVERTER_SOURCES+=packet_data_session_already_established.c
ASN_CONVERTER_SOURCES+=packet_data_session_failed.c
ASN_CONVERTER_SOURCES+=packet_data_header_report.c
ASN_CONVERTER_SOURCES+=packet_data_summary_report.c
ASN_CONVERTER_SOURCES+=ias_cc_apdu.c

lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = IAS 
CFLAGS += -I. -I/opencalea/T1.IAS/CmII -I/opencalea/T1.IAS/CmCC -I/opencalea/T1.678/VoP
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	asn1c -fskeletons-copy -fnative-types -fcompound-names IAS-LAES-CmII-Abstract-Syntax-Module.asn

