/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_CCCIdentity_H_
#define	_CCCIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CCCIdentity_PR {
	CCCIdentity_PR_NOTHING,	/* No components present */
	CCCIdentity_PR_combCCC,
	CCCIdentity_PR_sepCCCpair,
	CCCIdentity_PR_indXmitCCC,
	CCCIdentity_PR_indRecvCCC,
	CCCIdentity_PR_indCCC
} CCCIdentity_PR;

/* CCCIdentity */
typedef struct CCCIdentity {
	CCCIdentity_PR present;
	union CCCIdentity_u {
		VisibleString_t	 combCCC;
		struct CCCIdentity__sepCCCpair {
			VisibleString_t	 sepXmitCCC;
			VisibleString_t	 sepRecvCCC;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} sepCCCpair;
		VisibleString_t	 indXmitCCC;
		VisibleString_t	 indRecvCCC;
		VisibleString_t	 indCCC;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CCCIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CCCIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _CCCIdentity_H_ */
