/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_IAS_CCDeliveryFormat_H_
#define	_IAS_CCDeliveryFormat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "IAS-LAES-CmCC-Module-OID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IAS_CCDeliveryFormat_PR {
	IAS_CCDeliveryFormat_PR_NOTHING,	/* No components present */
	IAS_CCDeliveryFormat_PR_scteDatagram,
	IAS_CCDeliveryFormat_PR_atis_678_ASN1,
	IAS_CCDeliveryFormat_PR_iasDatagram
} IAS_CCDeliveryFormat_PR;

/* IAS-CCDeliveryFormat */
typedef struct IAS_CCDeliveryFormat {
	IAS_CCDeliveryFormat_PR present;
	union IAS_CCDeliveryFormat_u {
		NULL_t	 scteDatagram;
		IAS_LAES_CmCC_Module_OID_t	 atis_678_ASN1;
		NULL_t	 iasDatagram;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IAS_CCDeliveryFormat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IAS_CCDeliveryFormat;

#ifdef __cplusplus
}
#endif

#endif	/* _IAS_CCDeliveryFormat_H_ */
