/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "IPAddress.h"

static asn_TYPE_member_t asn_MBR_allocationMethod_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress__allocationMethod, choice.Static),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"static"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress__allocationMethod, choice.dynamic),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dynamic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress__allocationMethod, choice.unknown),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unknown"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress__allocationMethod, choice.notApplicable),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notApplicable"
		},
};
static asn_TYPE_tag2member_t asn_MAP_allocationMethod_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* static at 176 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dynamic at 177 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* unknown at 178 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* notApplicable at 179 */
};
static asn_CHOICE_specifics_t asn_SPC_allocationMethod_specs_3 = {
	sizeof(struct IPAddress__allocationMethod),
	offsetof(struct IPAddress__allocationMethod, _asn_ctx),
	offsetof(struct IPAddress__allocationMethod, present),
	sizeof(((struct IPAddress__allocationMethod *)0)->present),
	asn_MAP_allocationMethod_tag2el_3,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_allocationMethod_3 = {
	"allocationMethod",
	"allocationMethod",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_allocationMethod_3,
	4,	/* Elements count */
	&asn_SPC_allocationMethod_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IPAddress_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress, address),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IpAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPAddress, allocationMethod),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_allocationMethod_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allocationMethod"
		},
	{ ATF_POINTER, 2, offsetof(struct IPAddress, iPv6FlowLabel),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iPv6FlowLabel"
		},
	{ ATF_POINTER, 1, offsetof(struct IPAddress, prefixLen),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prefixLen"
		},
};
static ber_tlv_tag_t asn_DEF_IPAddress_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_IPAddress_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* address at 174 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* allocationMethod at 176 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* iPv6FlowLabel at 181 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* prefixLen at 182 */
};
static asn_SEQUENCE_specifics_t asn_SPC_IPAddress_specs_1 = {
	sizeof(struct IPAddress),
	offsetof(struct IPAddress, _asn_ctx),
	asn_MAP_IPAddress_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IPAddress = {
	"IPAddress",
	"IPAddress",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IPAddress_tags_1,
	sizeof(asn_DEF_IPAddress_tags_1)
		/sizeof(asn_DEF_IPAddress_tags_1[0]), /* 1 */
	asn_DEF_IPAddress_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPAddress_tags_1)
		/sizeof(asn_DEF_IPAddress_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IPAddress_1,
	4,	/* Elements count */
	&asn_SPC_IPAddress_specs_1	/* Additional specs */
};

