/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "NetworkAccessNodeIdentity.h"

int
NetworkAccessNodeIdentity_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_Value.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using Value,
 * so here we adjust the DEF accordingly.
 */
static void
NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_Value.free_struct;
	td->print_struct   = asn_DEF_Value.print_struct;
	td->ber_decoder    = asn_DEF_Value.ber_decoder;
	td->der_encoder    = asn_DEF_Value.der_encoder;
	td->xer_decoder    = asn_DEF_Value.xer_decoder;
	td->xer_encoder    = asn_DEF_Value.xer_encoder;
	td->uper_decoder   = asn_DEF_Value.uper_decoder;
	td->uper_encoder   = asn_DEF_Value.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_Value.per_constraints;
	td->elements       = asn_DEF_Value.elements;
	td->elements_count = asn_DEF_Value.elements_count;
	td->specifics      = asn_DEF_Value.specifics;
}

void
NetworkAccessNodeIdentity_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
NetworkAccessNodeIdentity_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
NetworkAccessNodeIdentity_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
NetworkAccessNodeIdentity_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
NetworkAccessNodeIdentity_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
NetworkAccessNodeIdentity_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	NetworkAccessNodeIdentity_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_TYPE_descriptor_t asn_DEF_NetworkAccessNodeIdentity = {
	"NetworkAccessNodeIdentity",
	"NetworkAccessNodeIdentity",
	NetworkAccessNodeIdentity_free,
	NetworkAccessNodeIdentity_print,
	NetworkAccessNodeIdentity_constraint,
	NetworkAccessNodeIdentity_decode_ber,
	NetworkAccessNodeIdentity_encode_der,
	NetworkAccessNodeIdentity_decode_xer,
	NetworkAccessNodeIdentity_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};

