/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "Packet-Data-Session-Failed.h"

static asn_TYPE_member_t asn_MBR_Packet_Data_Session_Failed_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Packet_Data_Session_Failed, caseId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CaseIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caseId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Packet_Data_Session_Failed, iAPSystemId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IAPSystemIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iAPSystemId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Packet_Data_Session_Failed, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timestamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Packet_Data_Session_Failed, subscriberIdentity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SubscriberIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subscriberIdentity"
		},
	{ ATF_POINTER, 2, offsetof(struct Packet_Data_Session_Failed, accessSessionID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AccessSessionID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessSessionID"
		},
	{ ATF_POINTER, 1, offsetof(struct Packet_Data_Session_Failed, reasonForTermination),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReasonForTermination,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reasonForTermination"
		},
};
static ber_tlv_tag_t asn_DEF_Packet_Data_Session_Failed_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Packet_Data_Session_Failed_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* caseId at 109 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iAPSystemId at 110 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timestamp at 111 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* subscriberIdentity at 112 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* accessSessionID at 113 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* reasonForTermination at 114 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Packet_Data_Session_Failed_specs_1 = {
	sizeof(struct Packet_Data_Session_Failed),
	offsetof(struct Packet_Data_Session_Failed, _asn_ctx),
	asn_MAP_Packet_Data_Session_Failed_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Packet_Data_Session_Failed = {
	"Packet-Data-Session-Failed",
	"Packet-Data-Session-Failed",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Packet_Data_Session_Failed_tags_1,
	sizeof(asn_DEF_Packet_Data_Session_Failed_tags_1)
		/sizeof(asn_DEF_Packet_Data_Session_Failed_tags_1[0]), /* 1 */
	asn_DEF_Packet_Data_Session_Failed_tags_1,	/* Same as above */
	sizeof(asn_DEF_Packet_Data_Session_Failed_tags_1)
		/sizeof(asn_DEF_Packet_Data_Session_Failed_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Packet_Data_Session_Failed_1,
	6,	/* Elements count */
	&asn_SPC_Packet_Data_Session_Failed_specs_1	/* Additional specs */
};

