/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmII-Optional-Messages-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmII-Optional-Messages-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "VPNSecurityAssociationProtocols.h"

static asn_TYPE_member_t asn_MBR_VPNSecurityAssociationProtocols_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_VPNSecurityAssociationProtocols_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_VPNSecurityAssociationProtocols_specs_1 = {
	sizeof(struct VPNSecurityAssociationProtocols),
	offsetof(struct VPNSecurityAssociationProtocols, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_VPNSecurityAssociationProtocols = {
	"VPNSecurityAssociationProtocols",
	"VPNSecurityAssociationProtocols",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VPNSecurityAssociationProtocols_tags_1,
	sizeof(asn_DEF_VPNSecurityAssociationProtocols_tags_1)
		/sizeof(asn_DEF_VPNSecurityAssociationProtocols_tags_1[0]), /* 1 */
	asn_DEF_VPNSecurityAssociationProtocols_tags_1,	/* Same as above */
	sizeof(asn_DEF_VPNSecurityAssociationProtocols_tags_1)
		/sizeof(asn_DEF_VPNSecurityAssociationProtocols_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VPNSecurityAssociationProtocols_1,
	1,	/* Single element */
	&asn_SPC_VPNSecurityAssociationProtocols_specs_1	/* Additional specs */
};

