ASN_MODULE_SOURCES=	\
	/opencalea/T1.678/VoP/T1S1-LAES-VoP-Abstract-Syntax-Module-OID.c	\
	/opencalea/T1.678/VoP/LAESProtocol.c	\
	/opencalea/T1.678/VoP/EnhancedProtocol.c	\
	/opencalea/T1.678/VoP/LaesMessage.c	\
	/opencalea/T1.678/VoP/Answer.c	\
	/opencalea/T1.678/VoP/CCChange.c	\
	/opencalea/T1.678/VoP/CCClose.c	\
	/opencalea/T1.678/VoP/CCOpen.c	\
	/opencalea/T1.678/VoP/CCUnavailable.c	\
	/opencalea/T1.678/VoP/Change.c	\
	/opencalea/T1.678/VoP/Connection.c	\
	/opencalea/T1.678/VoP/ConnectionBreak.c	\
	/opencalea/T1.678/VoP/ConfPartyChange.c	\
	/opencalea/T1.678/VoP/DialedDigitExtraction.c	\
	/opencalea/T1.678/VoP/DirectSignalReporting.c	\
	/opencalea/T1.678/VoP/MediaAndAddressReporting.c	\
	/opencalea/T1.678/VoP/NetworkSignal.c	\
	/opencalea/T1.678/VoP/Origination.c	\
	/opencalea/T1.678/VoP/Redirection.c	\
	/opencalea/T1.678/VoP/Release.c	\
	/opencalea/T1.678/VoP/ServingSystem.c	\
	/opencalea/T1.678/VoP/Generic.c	\
	/opencalea/T1.678/VoP/SubjectSignal.c	\
	/opencalea/T1.678/VoP/TerminationAttempt.c	\
	/opencalea/T1.678/VoP/UUContent.c	\
	/opencalea/T1.678/VoP/AddressRegistrationType.c	\
	/opencalea/T1.678/VoP/AdmissionControlStatus.c	\
	/opencalea/T1.678/VoP/CallIdentity.c	\
	/opencalea/T1.678/VoP/Cause.c	\
	/opencalea/T1.678/VoP/CCAddress.c	\
	/opencalea/T1.678/VoP/CCDeliveryFormat.c	\
	/opencalea/T1.678/VoP/ContentIdentifier.c	\
	/opencalea/T1.678/VoP/CorrelationIdentifier.c	\
	/opencalea/T1.678/VoP/DeliveryIdentifier.c	\
	/opencalea/T1.678/VoP/ForkedCallInformation.c	\
	/opencalea/T1.678/VoP/EncapsulatedSignalingMessage.c	\
	/opencalea/T1.678/VoP/H225CallSignaling.c	\
	/opencalea/T1.678/VoP/H245.c	\
	/opencalea/T1.678/VoP/H323CallTransfer.c	\
	/opencalea/T1.678/VoP/H323Media.c	\
	/opencalea/T1.678/VoP/H323MediaParameterType.c	\
	/opencalea/T1.678/VoP/IpAddress.c	\
	/opencalea/T1.678/VoP/IPvalue.c	\
	/opencalea/T1.678/VoP/Location.c	\
	/opencalea/T1.678/VoP/MediaInformation.c	\
	/opencalea/T1.678/VoP/ParameterFormat.c	\
	/opencalea/T1.678/VoP/PartyIdentity.c	\
	/opencalea/T1.678/VoP/PortNumber.c	\
	/opencalea/T1.678/VoP/ProtocolSpecificParameters.c	\
	/opencalea/T1.678/VoP/SipHeader.c	\
	/opencalea/T1.678/VoP/SurveillanceStatus.c	\
	/opencalea/T1.678/VoP/CurrentSurveillanceStatus.c	\
	/opencalea/T1.678/VoP/SurveillanceStatusEventType.c	\
	/opencalea/T1.678/VoP/FeatureManagement.c	\
	/opencalea/T1.678/VoP/FeatureManagementType.c	\
	/opencalea/T1.678/VoP/CCDeliveryHeaderModuleOID.c	\
	/opencalea/T1.678/VoP/CC-APDU.c	\
	/opencalea/T1.678/VoP/CCDeliveryHeader.c	\
	/opencalea/T1.678/VoP/PacketDirection.c	\
	/opencalea/T1.678/VoP/AlertingSignal.c	\
	/opencalea/T1.678/VoP/AudibleSignal.c	\
	/opencalea/T1.678/VoP/BearerCapability.c	\
	/opencalea/T1.678/VoP/CaseIdentity.c	\
	/opencalea/T1.678/VoP/CCCIdentity.c	\
	/opencalea/T1.678/VoP/IAPSystemIdentity.c	\
	/opencalea/T1.678/VoP/TimeStamp.c	\
	/opencalea/T1.678/VoP/TerminalDisplayInfo.c	\
	/opencalea/T1.678/VoP/TransitCarrierIdentity.c	\
	/opencalea/T1.678/VoP/RedirectedFromInformation.c

ASN_MODULE_HEADERS=	\
	T1S1-LAES-VoP-Abstract-Syntax-Module-OID.h	\
	LAESProtocol.h	\
	EnhancedProtocol.h	\
	LaesMessage.h	\
	Answer.h	\
	CCChange.h	\
	CCClose.h	\
	CCOpen.h	\
	CCUnavailable.h	\
	Change.h	\
	Connection.h	\
	ConnectionBreak.h	\
	ConfPartyChange.h	\
	DialedDigitExtraction.h	\
	DirectSignalReporting.h	\
	MediaAndAddressReporting.h	\
	NetworkSignal.h	\
	Origination.h	\
	Redirection.h	\
	Release.h	\
	ServingSystem.h	\
	Generic.h	\
	SubjectSignal.h	\
	TerminationAttempt.h	\
	UUContent.h	\
	AddressRegistrationType.h	\
	AdmissionControlStatus.h	\
	CallIdentity.h	\
	Cause.h	\
	CCAddress.h	\
	CCDeliveryFormat.h	\
	ContentIdentifier.h	\
	CorrelationIdentifier.h	\
	DeliveryIdentifier.h	\
	ForkedCallInformation.h	\
	EncapsulatedSignalingMessage.h	\
	H225CallSignaling.h	\
	H245.h	\
	H323CallTransfer.h	\
	H323Media.h	\
	H323MediaParameterType.h	\
	IpAddress.h	\
	IPvalue.h	\
	Location.h	\
	MediaInformation.h	\
	ParameterFormat.h	\
	PartyIdentity.h	\
	PortNumber.h	\
	ProtocolSpecificParameters.h	\
	SipHeader.h	\
	SurveillanceStatus.h	\
	CurrentSurveillanceStatus.h	\
	SurveillanceStatusEventType.h	\
	FeatureManagement.h	\
	FeatureManagementType.h	\
	CCDeliveryHeaderModuleOID.h	\
	CC-APDU.h	\
	CCDeliveryHeader.h	\
	PacketDirection.h	\
	AlertingSignal.h	\
	AudibleSignal.h	\
	BearerCapability.h	\
	CaseIdentity.h	\
	CCCIdentity.h	\
	IAPSystemIdentity.h	\
	TimeStamp.h	\
	TerminalDisplayInfo.h	\
	TransitCarrierIdentity.h	\
	RedirectedFromInformation.h

ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/UTF8String.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/BOOLEAN.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/BOOLEAN.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/INTEGER.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/NativeEnumerated.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/GeneralizedTime.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/GeneralizedTime.c
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/INTEGER.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/NULL.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/NULL.c
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/NativeEnumerated.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/NativeInteger.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/NativeInteger.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/OBJECT_IDENTIFIER.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/OBJECT_IDENTIFIER.c
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/UTF8String.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/VisibleString.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/VisibleString.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_SET_OF.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/asn_SET_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_CHOICE.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_CHOICE.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_SEQUENCE.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_SEQUENCE.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_SET_OF.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_SET.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_SET.c
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_SET_OF.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_application.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_system.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_codecs.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_internal.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/OCTET_STRING.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/OCTET_STRING.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/BIT_STRING.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/BIT_STRING.c
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/asn_codecs_prim.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/asn_codecs_prim.h
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/ber_tlv_length.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/ber_tlv_length.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/ber_tlv_tag.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/ber_tlv_tag.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/ber_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/ber_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/der_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/der_encoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constr_TYPE.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constr_TYPE.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/constraints.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/constraints.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/xer_support.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/xer_support.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/xer_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/xer_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/xer_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/xer_encoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/per_support.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/per_support.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/per_decoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/per_decoder.c
ASN_MODULE_HEADERS+=/opencalea/T1.678/VoP/per_encoder.h
ASN_MODULE_SOURCES+=/opencalea/T1.678/VoP/per_encoder.c
ASN_CONVERTER_SOURCES+=main.c
ASN_CONVERTER_SOURCES+=routines.c
ASN_CONVERTER_SOURCES+=answer.c
ASN_CONVERTER_SOURCES+=ccclose.c
ASN_CONVERTER_SOURCES+=ccopen.c
ASN_CONVERTER_SOURCES+=change.c
ASN_CONVERTER_SOURCES+=ccchange.c
ASN_CONVERTER_SOURCES+=ccunavailable.c
ASN_CONVERTER_SOURCES+=redirection.c
ASN_CONVERTER_SOURCES+=release.c
ASN_CONVERTER_SOURCES+=origination.c
ASN_CONVERTER_SOURCES+=servingsystem.c
ASN_CONVERTER_SOURCES+=subjectsignal.c
ASN_CONVERTER_SOURCES+=termattempt.c
ASN_CONVERTER_SOURCES+=uucontent.c
ASN_CONVERTER_SOURCES+=confpartychange.c
ASN_CONVERTER_SOURCES+=connection.c
ASN_CONVERTER_SOURCES+=connectionbreak.c
ASN_CONVERTER_SOURCES+=dialeddgtextrn.c
ASN_CONVERTER_SOURCES+=networksignal.c
ASN_CONVERTER_SOURCES+=directsignalreporting.c
ASN_CONVERTER_SOURCES+=mediaandaddressreporting.c
ASN_CONVERTER_SOURCES+=cc_apdu.c

lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = LAES
CFLAGS += -I. -I/opencalea/T1.678/VoP -I/opencalea/T1.678/CCDeliveryHeader
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	asn1c -fskeletons-copy -fnative-types -fcompound-names T1S1-LAES-VoP-Abstract-Syntax-Module.asn

