/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "IAS-LAES-CmCC-Abstract-Syntax-Module"
 * 	found in "IAS-LAES-CmCC-Abstract-Syntax-Module.asn"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "ContentIdentifier.h"

static asn_TYPE_member_t asn_MBR_ContentIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ContentIdentifier, choice.correlationID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CorrelationIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"correlationID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ContentIdentifier, choice.callID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callID"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ContentIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* correlationID at 56 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* callID at 58 */
};
static asn_CHOICE_specifics_t asn_SPC_ContentIdentifier_specs_1 = {
	sizeof(struct ContentIdentifier),
	offsetof(struct ContentIdentifier, _asn_ctx),
	offsetof(struct ContentIdentifier, present),
	sizeof(((struct ContentIdentifier *)0)->present),
	asn_MAP_ContentIdentifier_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ContentIdentifier = {
	"ContentIdentifier",
	"ContentIdentifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ContentIdentifier_1,
	2,	/* Elements count */
	&asn_SPC_ContentIdentifier_specs_1	/* Additional specs */
};

