/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "CCDeliveryHeader.h"

static asn_TYPE_member_t asn_MBR_correlationInfo_2[] = {
	{ ATF_POINTER, 2, offsetof(struct CCDeliveryHeader__correlationInfo, caseId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CaseIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caseId"
		},
	{ ATF_POINTER, 1, offsetof(struct CCDeliveryHeader__correlationInfo, iapId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IAPSystemIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iapId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CCDeliveryHeader__correlationInfo, contentIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ContentIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentIdentifier"
		},
};
static ber_tlv_tag_t asn_DEF_correlationInfo_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_correlationInfo_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* caseId at 612 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iapId at 613 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* contentIdentifier at 614 */
};
static asn_SEQUENCE_specifics_t asn_SPC_correlationInfo_specs_2 = {
	sizeof(struct CCDeliveryHeader__correlationInfo),
	offsetof(struct CCDeliveryHeader__correlationInfo, _asn_ctx),
	asn_MAP_correlationInfo_tag2el_2,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_correlationInfo_2 = {
	"correlationInfo",
	"correlationInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_correlationInfo_tags_2,
	sizeof(asn_DEF_correlationInfo_tags_2)
		/sizeof(asn_DEF_correlationInfo_tags_2[0]) - 1, /* 1 */
	asn_DEF_correlationInfo_tags_2,	/* Same as above */
	sizeof(asn_DEF_correlationInfo_tags_2)
		/sizeof(asn_DEF_correlationInfo_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_correlationInfo_2,
	3,	/* Elements count */
	&asn_SPC_correlationInfo_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CCDeliveryHeader_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CCDeliveryHeader, correlationInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_correlationInfo_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"correlationInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct CCDeliveryHeader, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeStamp"
		},
	{ ATF_POINTER, 2, offsetof(struct CCDeliveryHeader, packetDirection),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PacketDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packetDirection"
		},
	{ ATF_POINTER, 1, offsetof(struct CCDeliveryHeader, sequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sequenceNumber"
		},
};
static ber_tlv_tag_t asn_DEF_CCDeliveryHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CCDeliveryHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* correlationInfo at 612 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeStamp at 615 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* packetDirection at 616 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* sequenceNumber at 617 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CCDeliveryHeader_specs_1 = {
	sizeof(struct CCDeliveryHeader),
	offsetof(struct CCDeliveryHeader, _asn_ctx),
	asn_MAP_CCDeliveryHeader_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CCDeliveryHeader = {
	"CCDeliveryHeader",
	"CCDeliveryHeader",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CCDeliveryHeader_tags_1,
	sizeof(asn_DEF_CCDeliveryHeader_tags_1)
		/sizeof(asn_DEF_CCDeliveryHeader_tags_1[0]), /* 1 */
	asn_DEF_CCDeliveryHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_CCDeliveryHeader_tags_1)
		/sizeof(asn_DEF_CCDeliveryHeader_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CCDeliveryHeader_1,
	4,	/* Elements count */
	&asn_SPC_CCDeliveryHeader_specs_1	/* Additional specs */
};

