/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "EnhancedProtocol.h"

static asn_TYPE_member_t asn_MBR_EnhancedProtocol_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnhancedProtocol, protocolIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_T1S1_LAES_VoP_Abstract_Syntax_Module_OID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnhancedProtocol, laesMessage),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_LaesMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"laesMessage"
		},
};
static ber_tlv_tag_t asn_DEF_EnhancedProtocol_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_EnhancedProtocol_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* protocolIdentifier at 19 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* answer at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ccClose at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* ccOpen at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* change at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* origination at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* null-6 at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 0 }, /* redirection at 30 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 1, 0, 0 }, /* release at 31 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 0 }, /* servingSystem at 32 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 1, 0, 0 }, /* termAttempt at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 }, /* confPartyChange at 35 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 1, 0, 0 }, /* connection at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 1, 0, 0 }, /* connectionBreak at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 1, 0, 0 }, /* dialedDgtExtrn at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 1, 0, 0 }, /* networkSignal at 39 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* subjectSignal at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 }, /* directSignalReporting at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 1, 0, 0 }, /* mediaAndAddressReporting at 42 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 1, 0, 0 }, /* ccChange at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 1, 0, 0 }, /* ccUnavailable at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 1, 0, 0 }, /* surveillanceStatus at 45 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 1, 0, 0 }, /* featureManagement at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 1, 0, 0 } /* uuContent at 48 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EnhancedProtocol_specs_1 = {
	sizeof(struct EnhancedProtocol),
	offsetof(struct EnhancedProtocol, _asn_ctx),
	asn_MAP_EnhancedProtocol_tag2el_1,
	24,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EnhancedProtocol = {
	"EnhancedProtocol",
	"EnhancedProtocol",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EnhancedProtocol_tags_1,
	sizeof(asn_DEF_EnhancedProtocol_tags_1)
		/sizeof(asn_DEF_EnhancedProtocol_tags_1[0]), /* 1 */
	asn_DEF_EnhancedProtocol_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnhancedProtocol_tags_1)
		/sizeof(asn_DEF_EnhancedProtocol_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EnhancedProtocol_1,
	2,	/* Elements count */
	&asn_SPC_EnhancedProtocol_specs_1	/* Additional specs */
};

