/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "LaesMessage.h"

static asn_TYPE_member_t asn_MBR_LaesMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.answer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Answer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"answer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.ccClose),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CCClose,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccClose"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.ccOpen),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CCOpen,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccOpen"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.change),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Change,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"change"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.origination),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Origination,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"origination"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.null_6),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"null-6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.redirection),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Redirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"redirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Release,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.servingSystem),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServingSystem,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingSystem"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.termAttempt),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TerminationAttempt,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"termAttempt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.confPartyChange),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConfPartyChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confPartyChange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.connection),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Connection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.connectionBreak),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConnectionBreak,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"connectionBreak"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.dialedDgtExtrn),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DialedDigitExtraction,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dialedDgtExtrn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.networkSignal),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NetworkSignal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkSignal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.subjectSignal),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectSignal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subjectSignal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.directSignalReporting),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DirectSignalReporting,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"directSignalReporting"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.mediaAndAddressReporting),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MediaAndAddressReporting,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mediaAndAddressReporting"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.ccChange),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CCChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccChange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.ccUnavailable),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CCUnavailable,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ccUnavailable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.surveillanceStatus),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SurveillanceStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"surveillanceStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.featureManagement),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FeatureManagement,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"featureManagement"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LaesMessage, choice.uuContent),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UUContent,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"uuContent"
		},
};
static asn_TYPE_tag2member_t asn_MAP_LaesMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* answer at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ccClose at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* ccOpen at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* change at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* origination at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* null-6 at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* redirection at 30 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* release at 31 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* servingSystem at 32 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 }, /* termAttempt at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 10, 0, 0 }, /* confPartyChange at 35 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 11, 0, 0 }, /* connection at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 12, 0, 0 }, /* connectionBreak at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 13, 0, 0 }, /* dialedDgtExtrn at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 14, 0, 0 }, /* networkSignal at 39 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 15, 0, 0 }, /* subjectSignal at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 16, 0, 0 }, /* directSignalReporting at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 17, 0, 0 }, /* mediaAndAddressReporting at 42 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 18, 0, 0 }, /* ccChange at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 19, 0, 0 }, /* ccUnavailable at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 20, 0, 0 }, /* surveillanceStatus at 45 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 21, 0, 0 }, /* featureManagement at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 22, 0, 0 } /* uuContent at 48 */
};
static asn_CHOICE_specifics_t asn_SPC_LaesMessage_specs_1 = {
	sizeof(struct LaesMessage),
	offsetof(struct LaesMessage, _asn_ctx),
	offsetof(struct LaesMessage, present),
	sizeof(((struct LaesMessage *)0)->present),
	asn_MAP_LaesMessage_tag2el_1,
	23,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LaesMessage = {
	"LaesMessage",
	"LaesMessage",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_LaesMessage_1,
	23,	/* Elements count */
	&asn_SPC_LaesMessage_specs_1	/* Additional specs */
};

