/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Origination_H_
#define	_Origination_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CaseIdentity.h"
#include "IAPSystemIdentity.h"
#include "TimeStamp.h"
#include "CallIdentity.h"
#include "TransitCarrierIdentity.h"
#include <VisibleString.h>
#include "PartyIdentity.h"
#include <constr_CHOICE.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Origination__input_PR {
	Origination__input_PR_NOTHING,	/* No components present */
	Origination__input_PR_userInput,
	Origination__input_PR_translationInput
} Origination__input_PR;
typedef enum Origination__input__userInput_PR {
	Origination__input__userInput_PR_NOTHING,	/* No components present */
	Origination__input__userInput_PR_generic,
	Origination__input__userInput_PR_specific
} Origination__input__userInput_PR;
typedef enum Origination__input__translationInput_PR {
	Origination__input__translationInput_PR_NOTHING,	/* No components present */
	Origination__input__translationInput_PR_generic,
	Origination__input__translationInput_PR_specific
} Origination__input__translationInput_PR;

/* Forward declarations */
struct PartyIdentity;
struct Location;
struct MediaInformation;
struct ProtocolSpecificParameters;
struct EncapsulatedSignalingMessage;
struct ForkedCallInformation;

/* Origination */
typedef struct Origination {
	CaseIdentity_t	 caseId;
	IAPSystemIdentity_t	*iAPSystemId	/* OPTIONAL */;
	TimeStamp_t	 timestamp;
	CallIdentity_t	 callId;
	struct PartyIdentity	*calling	/* OPTIONAL */;
	struct PartyIdentity	*called	/* OPTIONAL */;
	struct Origination__input {
		Origination__input_PR present;
		union Origination__input_u {
			struct Origination__input__userInput {
				Origination__input__userInput_PR present;
				union Origination__input__userInput_u {
					VisibleString_t	 generic;
					PartyIdentity_t	 specific;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} userInput;
			struct Origination__input__translationInput {
				Origination__input__translationInput_PR present;
				union Origination__input__translationInput_u {
					VisibleString_t	 generic;
					PartyIdentity_t	 specific;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} translationInput;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} input;
	struct Location	*location	/* OPTIONAL */;
	TransitCarrierIdentity_t	*transitCarrierId	/* OPTIONAL */;
	struct MediaInformation	*subjectMedia	/* OPTIONAL */;
	VisibleString_t	 originationCause;
	struct ProtocolSpecificParameters	*protocolSpecificParameters	/* OPTIONAL */;
	struct Origination__signalingMsg {
		A_SET_OF(struct EncapsulatedSignalingMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *signalingMsg;
	struct Origination__forkedCalls {
		A_SET_OF(struct ForkedCallInformation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *forkedCalls;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Origination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Origination;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PartyIdentity.h"
#include "Location.h"
#include "MediaInformation.h"
#include "ProtocolSpecificParameters.h"
#include "EncapsulatedSignalingMessage.h"
#include "ForkedCallInformation.h"

#endif	/* _Origination_H_ */
