/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "ServingSystem.h"

static int check_permitted_alphabet_5(const void *sptr) {
	/* The underlying type is VisibleString */
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv >= 32 && cv <= 126)) return -1;
	}
	return 0;
}

static int check_permitted_alphabet_6(const void *sptr) {
	/* The underlying type is VisibleString */
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv >= 32 && cv <= 126)) return -1;
	}
	return 0;
}

static int
memb_systemIdentity_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 15)
		 && !check_permitted_alphabet_5(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_networkAddress_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 15)
		 && !check_permitted_alphabet_6(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_generic_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Generic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_generic_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_generic_specs_13 = {
	sizeof(struct ServingSystem__requestAddressInfo__generic),
	offsetof(struct ServingSystem__requestAddressInfo__generic, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_generic_13 = {
	"generic",
	"generic",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_generic_tags_13,
	sizeof(asn_DEF_generic_tags_13)
		/sizeof(asn_DEF_generic_tags_13[0]) - 1, /* 1 */
	asn_DEF_generic_tags_13,	/* Same as above */
	sizeof(asn_DEF_generic_tags_13)
		/sizeof(asn_DEF_generic_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_generic_13,
	1,	/* Single element */
	&asn_SPC_generic_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sip_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_SipHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_sip_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sip_specs_15 = {
	sizeof(struct ServingSystem__requestAddressInfo__sip),
	offsetof(struct ServingSystem__requestAddressInfo__sip, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sip_15 = {
	"sip",
	"sip",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sip_tags_15,
	sizeof(asn_DEF_sip_tags_15)
		/sizeof(asn_DEF_sip_tags_15[0]) - 1, /* 1 */
	asn_DEF_sip_tags_15,	/* Same as above */
	sizeof(asn_DEF_sip_tags_15)
		/sizeof(asn_DEF_sip_tags_15[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sip_15,
	1,	/* Single element */
	&asn_SPC_sip_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_requestAddressInfo_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__requestAddressInfo, choice.generic),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_generic_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__requestAddressInfo, choice.sip),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_sip_15,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sip"
		},
};
static asn_TYPE_tag2member_t asn_MAP_requestAddressInfo_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* generic at 295 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sip at 296 */
};
static asn_CHOICE_specifics_t asn_SPC_requestAddressInfo_specs_12 = {
	sizeof(struct ServingSystem__requestAddressInfo),
	offsetof(struct ServingSystem__requestAddressInfo, _asn_ctx),
	offsetof(struct ServingSystem__requestAddressInfo, present),
	sizeof(((struct ServingSystem__requestAddressInfo *)0)->present),
	asn_MAP_requestAddressInfo_tag2el_12,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requestAddressInfo_12 = {
	"requestAddressInfo",
	"requestAddressInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_requestAddressInfo_12,
	2,	/* Elements count */
	&asn_SPC_requestAddressInfo_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_generic_18[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Generic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_generic_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_generic_specs_18 = {
	sizeof(struct ServingSystem__responseAddressInfo__generic),
	offsetof(struct ServingSystem__responseAddressInfo__generic, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_generic_18 = {
	"generic",
	"generic",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_generic_tags_18,
	sizeof(asn_DEF_generic_tags_18)
		/sizeof(asn_DEF_generic_tags_18[0]) - 1, /* 1 */
	asn_DEF_generic_tags_18,	/* Same as above */
	sizeof(asn_DEF_generic_tags_18)
		/sizeof(asn_DEF_generic_tags_18[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_generic_18,
	1,	/* Single element */
	&asn_SPC_generic_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sip_20[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_SipHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_sip_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sip_specs_20 = {
	sizeof(struct ServingSystem__responseAddressInfo__sip),
	offsetof(struct ServingSystem__responseAddressInfo__sip, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sip_20 = {
	"sip",
	"sip",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sip_tags_20,
	sizeof(asn_DEF_sip_tags_20)
		/sizeof(asn_DEF_sip_tags_20[0]) - 1, /* 1 */
	asn_DEF_sip_tags_20,	/* Same as above */
	sizeof(asn_DEF_sip_tags_20)
		/sizeof(asn_DEF_sip_tags_20[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sip_20,
	1,	/* Single element */
	&asn_SPC_sip_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_responseAddressInfo_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__responseAddressInfo, choice.generic),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_generic_18,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__responseAddressInfo, choice.sip),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_sip_20,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sip"
		},
};
static asn_TYPE_tag2member_t asn_MAP_responseAddressInfo_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* generic at 298 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sip at 299 */
};
static asn_CHOICE_specifics_t asn_SPC_responseAddressInfo_specs_17 = {
	sizeof(struct ServingSystem__responseAddressInfo),
	offsetof(struct ServingSystem__responseAddressInfo, _asn_ctx),
	offsetof(struct ServingSystem__responseAddressInfo, present),
	sizeof(((struct ServingSystem__responseAddressInfo *)0)->present),
	asn_MAP_responseAddressInfo_tag2el_17,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_responseAddressInfo_17 = {
	"responseAddressInfo",
	"responseAddressInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_responseAddressInfo_17,
	2,	/* Elements count */
	&asn_SPC_responseAddressInfo_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_expirationPeriod_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__expirationPeriod, choice.generic),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem__expirationPeriod, choice.sip),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SipHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sip"
		},
};
static asn_TYPE_tag2member_t asn_MAP_expirationPeriod_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* generic at 302 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sip at 303 */
};
static asn_CHOICE_specifics_t asn_SPC_expirationPeriod_specs_23 = {
	sizeof(struct ServingSystem__expirationPeriod),
	offsetof(struct ServingSystem__expirationPeriod, _asn_ctx),
	offsetof(struct ServingSystem__expirationPeriod, present),
	sizeof(((struct ServingSystem__expirationPeriod *)0)->present),
	asn_MAP_expirationPeriod_tag2el_23,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_expirationPeriod_23 = {
	"expirationPeriod",
	"expirationPeriod",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_expirationPeriod_23,
	2,	/* Elements count */
	&asn_SPC_expirationPeriod_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_signalingMsg_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EncapsulatedSignalingMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_signalingMsg_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_signalingMsg_specs_27 = {
	sizeof(struct ServingSystem__signalingMsg),
	offsetof(struct ServingSystem__signalingMsg, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_signalingMsg_27 = {
	"signalingMsg",
	"signalingMsg",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_signalingMsg_tags_27,
	sizeof(asn_DEF_signalingMsg_tags_27)
		/sizeof(asn_DEF_signalingMsg_tags_27[0]) - 1, /* 1 */
	asn_DEF_signalingMsg_tags_27,	/* Same as above */
	sizeof(asn_DEF_signalingMsg_tags_27)
		/sizeof(asn_DEF_signalingMsg_tags_27[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_signalingMsg_27,
	1,	/* Single element */
	&asn_SPC_signalingMsg_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ServingSystem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem, caseId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CaseIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caseId"
		},
	{ ATF_POINTER, 1, offsetof(struct ServingSystem, iAPSystemId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IAPSystemIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iAPSystemId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingSystem, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timestamp"
		},
	{ ATF_POINTER, 13, offsetof(struct ServingSystem, systemIdentity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		memb_systemIdentity_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"systemIdentity"
		},
	{ ATF_POINTER, 12, offsetof(struct ServingSystem, networkAddress),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		memb_networkAddress_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkAddress"
		},
	{ ATF_POINTER, 11, offsetof(struct ServingSystem, requestId),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestId"
		},
	{ ATF_POINTER, 10, offsetof(struct ServingSystem, registrationType),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AddressRegistrationType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"registrationType"
		},
	{ ATF_POINTER, 9, offsetof(struct ServingSystem, registering),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PartyIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"registering"
		},
	{ ATF_POINTER, 8, offsetof(struct ServingSystem, requesting),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PartyIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requesting"
		},
	{ ATF_POINTER, 7, offsetof(struct ServingSystem, registrar),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PartyIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"registrar"
		},
	{ ATF_POINTER, 6, offsetof(struct ServingSystem, requestAddressInfo),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_requestAddressInfo_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestAddressInfo"
		},
	{ ATF_POINTER, 5, offsetof(struct ServingSystem, responseAddressInfo),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_responseAddressInfo_17,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responseAddressInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct ServingSystem, failureReason),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cause,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"failureReason"
		},
	{ ATF_POINTER, 3, offsetof(struct ServingSystem, expirationPeriod),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_expirationPeriod_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"expirationPeriod"
		},
	{ ATF_POINTER, 2, offsetof(struct ServingSystem, protocolSpecificParameters),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProtocolSpecificParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolSpecificParameters"
		},
	{ ATF_POINTER, 1, offsetof(struct ServingSystem, signalingMsg),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		0,
		&asn_DEF_signalingMsg_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signalingMsg"
		},
};
static ber_tlv_tag_t asn_DEF_ServingSystem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServingSystem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* caseId at 284 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iAPSystemId at 285 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timestamp at 286 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* systemIdentity at 287 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* networkAddress at 288 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* requestId at 289 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* registrationType at 290 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* registering at 291 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* requesting at 292 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* registrar at 293 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* requestAddressInfo at 295 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* responseAddressInfo at 298 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* failureReason at 300 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* expirationPeriod at 302 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* protocolSpecificParameters at 304 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* signalingMsg at 305 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServingSystem_specs_1 = {
	sizeof(struct ServingSystem),
	offsetof(struct ServingSystem, _asn_ctx),
	asn_MAP_ServingSystem_tag2el_1,
	16,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServingSystem = {
	"ServingSystem",
	"ServingSystem",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServingSystem_tags_1,
	sizeof(asn_DEF_ServingSystem_tags_1)
		/sizeof(asn_DEF_ServingSystem_tags_1[0]), /* 1 */
	asn_DEF_ServingSystem_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServingSystem_tags_1)
		/sizeof(asn_DEF_ServingSystem_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ServingSystem_1,
	16,	/* Elements count */
	&asn_SPC_ServingSystem_specs_1	/* Additional specs */
};

