/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ServingSystem_H_
#define	_ServingSystem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CaseIdentity.h"
#include "IAPSystemIdentity.h"
#include "TimeStamp.h"
#include <VisibleString.h>
#include "AddressRegistrationType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "SipHeader.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_CHOICE.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingSystem__requestAddressInfo_PR {
	ServingSystem__requestAddressInfo_PR_NOTHING,	/* No components present */
	ServingSystem__requestAddressInfo_PR_generic,
	ServingSystem__requestAddressInfo_PR_sip
} ServingSystem__requestAddressInfo_PR;
typedef enum ServingSystem__responseAddressInfo_PR {
	ServingSystem__responseAddressInfo_PR_NOTHING,	/* No components present */
	ServingSystem__responseAddressInfo_PR_generic,
	ServingSystem__responseAddressInfo_PR_sip
} ServingSystem__responseAddressInfo_PR;
typedef enum ServingSystem__expirationPeriod_PR {
	ServingSystem__expirationPeriod_PR_NOTHING,	/* No components present */
	ServingSystem__expirationPeriod_PR_generic,
	ServingSystem__expirationPeriod_PR_sip
} ServingSystem__expirationPeriod_PR;

/* Forward declarations */
struct CallIdentity;
struct PartyIdentity;
struct Cause;
struct ProtocolSpecificParameters;
struct Generic;
struct EncapsulatedSignalingMessage;

/* ServingSystem */
typedef struct ServingSystem {
	CaseIdentity_t	 caseId;
	IAPSystemIdentity_t	*iAPSystemId	/* OPTIONAL */;
	TimeStamp_t	 timestamp;
	VisibleString_t	*systemIdentity	/* OPTIONAL */;
	VisibleString_t	*networkAddress	/* OPTIONAL */;
	struct CallIdentity	*requestId	/* OPTIONAL */;
	AddressRegistrationType_t	*registrationType	/* OPTIONAL */;
	struct PartyIdentity	*registering	/* OPTIONAL */;
	struct PartyIdentity	*requesting	/* OPTIONAL */;
	struct PartyIdentity	*registrar	/* OPTIONAL */;
	struct ServingSystem__requestAddressInfo {
		ServingSystem__requestAddressInfo_PR present;
		union ServingSystem__requestAddressInfo_u {
			struct ServingSystem__requestAddressInfo__generic {
				A_SEQUENCE_OF(struct Generic) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} generic;
			struct ServingSystem__requestAddressInfo__sip {
				A_SET_OF(SipHeader_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} sip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *requestAddressInfo;
	struct ServingSystem__responseAddressInfo {
		ServingSystem__responseAddressInfo_PR present;
		union ServingSystem__responseAddressInfo_u {
			struct ServingSystem__responseAddressInfo__generic {
				A_SEQUENCE_OF(struct Generic) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} generic;
			struct ServingSystem__responseAddressInfo__sip {
				A_SET_OF(SipHeader_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} sip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *responseAddressInfo;
	struct Cause	*failureReason	/* OPTIONAL */;
	struct ServingSystem__expirationPeriod {
		ServingSystem__expirationPeriod_PR present;
		union ServingSystem__expirationPeriod_u {
			long	 generic;
			SipHeader_t	 sip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *expirationPeriod;
	struct ProtocolSpecificParameters	*protocolSpecificParameters	/* OPTIONAL */;
	struct ServingSystem__signalingMsg {
		A_SET_OF(struct EncapsulatedSignalingMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *signalingMsg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServingSystem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingSystem;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CallIdentity.h"
#include "PartyIdentity.h"
#include "Cause.h"
#include "ProtocolSpecificParameters.h"
#include "Generic.h"
#include "EncapsulatedSignalingMessage.h"

#endif	/* _ServingSystem_H_ */
