/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#ifndef	_AudibleSignal_H_
#define	_AudibleSignal_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AudibleSignal {
	AudibleSignal_notUsed	= 0,
	AudibleSignal_dialTone	= 1,
	AudibleSignal_recallDialTone	= 2,
	AudibleSignal_ringbackTone	= 3,
	AudibleSignal_reorderTone	= 4,
	AudibleSignal_busyTone	= 5,
	AudibleSignal_confirmationTone	= 6,
	AudibleSignal_expensiveRouteTone	= 7,
	AudibleSignal_messageWaitingTone	= 8,
	AudibleSignal_receiverOffHookTone	= 9,
	AudibleSignal_specialInfoTone	= 10,
	AudibleSignal_denialTone	= 11,
	AudibleSignal_interceptTone	= 12,
	AudibleSignal_answerTone	= 13,
	AudibleSignal_tonesOff	= 14,
	AudibleSignal_pipTone	= 15,
	AudibleSignal_abbreviatedIntercept	= 16,
	AudibleSignal_abbreviatedCongestion	= 17,
	AudibleSignal_warningTone	= 18,
	AudibleSignal_dialToneBurst	= 19,
	AudibleSignal_numberUnObtainableTone	= 20,
	AudibleSignal_authenticationFailTone	= 21
} e_AudibleSignal;

/* AudibleSignal */
typedef long	 AudibleSignal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AudibleSignal;
asn_struct_free_f AudibleSignal_free;
asn_struct_print_f AudibleSignal_print;
asn_constr_check_f AudibleSignal_constraint;
ber_type_decoder_f AudibleSignal_decode_ber;
der_type_encoder_f AudibleSignal_encode_der;
xer_type_decoder_f AudibleSignal_decode_xer;
xer_type_encoder_f AudibleSignal_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AudibleSignal_H_ */
