/*
 * This file is autogenerated by the ASN.1 compiler.
 * Copyright (c) 2003-2007 Lev Walkin <vlm@lionet.info>
 * See http://lionet.info/asn1c
 *
 * Source ASN.1 file is Copyright (c) by US CALEA, included
 * with permission (if included). <<< this depends on whether
 * or not you include the original ASN.1 file into OpenCALEA >>>
 *
 * This file is part of OpenCALEA suite (http://opencalea.org)
 * and is subject to OpenCALEA license (see COPYING file in the
 * root of the opencalea distribution).
 *
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 *
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -fnative-types`
 */

#include <asn_internal.h>

#include "Change.h"

static asn_TYPE_member_t asn_MBR_call_identities_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CallIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_call_identities_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_call_identities_specs_6 = {
	sizeof(struct Change__previous__call_identities),
	offsetof(struct Change__previous__call_identities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_call_identities_6 = {
	"call-identities",
	"call-identities",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_call_identities_tags_6,
	sizeof(asn_DEF_call_identities_tags_6)
		/sizeof(asn_DEF_call_identities_tags_6[0]), /* 1 */
	asn_DEF_call_identities_tags_6,	/* Same as above */
	sizeof(asn_DEF_call_identities_tags_6)
		/sizeof(asn_DEF_call_identities_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_call_identities_6,
	1,	/* Single element */
	&asn_SPC_call_identities_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_previous_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Change__previous, call_identities),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_call_identities_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"call-identities"
		},
};
static ber_tlv_tag_t asn_DEF_previous_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_previous_tag2el_5[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* call-identities at 120 */
};
static asn_SEQUENCE_specifics_t asn_SPC_previous_specs_5 = {
	sizeof(struct Change__previous),
	offsetof(struct Change__previous, _asn_ctx),
	asn_MAP_previous_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_previous_5 = {
	"previous",
	"previous",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_previous_tags_5,
	sizeof(asn_DEF_previous_tags_5)
		/sizeof(asn_DEF_previous_tags_5[0]) - 1, /* 1 */
	asn_DEF_previous_tags_5,	/* Same as above */
	sizeof(asn_DEF_previous_tags_5)
		/sizeof(asn_DEF_previous_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_previous_5,
	1,	/* Elements count */
	&asn_SPC_previous_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_call_identities_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CallIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_call_identities_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_call_identities_specs_9 = {
	sizeof(struct Change__resulting__call_identities),
	offsetof(struct Change__resulting__call_identities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_call_identities_9 = {
	"call-identities",
	"call-identities",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_call_identities_tags_9,
	sizeof(asn_DEF_call_identities_tags_9)
		/sizeof(asn_DEF_call_identities_tags_9[0]) - 1, /* 1 */
	asn_DEF_call_identities_tags_9,	/* Same as above */
	sizeof(asn_DEF_call_identities_tags_9)
		/sizeof(asn_DEF_call_identities_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_call_identities_9,
	1,	/* Single element */
	&asn_SPC_call_identities_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_resulting_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Change__resulting, call_identities),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_call_identities_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"call-identities"
		},
	{ ATF_POINTER, 1, offsetof(struct Change__resulting, deliveryIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DeliveryIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"deliveryIdentifier"
		},
};
static ber_tlv_tag_t asn_DEF_resulting_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_resulting_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* call-identities at 122 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* deliveryIdentifier at 123 */
};
static asn_SEQUENCE_specifics_t asn_SPC_resulting_specs_8 = {
	sizeof(struct Change__resulting),
	offsetof(struct Change__resulting, _asn_ctx),
	asn_MAP_resulting_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resulting_8 = {
	"resulting",
	"resulting",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_resulting_tags_8,
	sizeof(asn_DEF_resulting_tags_8)
		/sizeof(asn_DEF_resulting_tags_8[0]) - 1, /* 1 */
	asn_DEF_resulting_tags_8,	/* Same as above */
	sizeof(asn_DEF_resulting_tags_8)
		/sizeof(asn_DEF_resulting_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_resulting_8,
	2,	/* Elements count */
	&asn_SPC_resulting_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_signalingMsg_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EncapsulatedSignalingMessage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_signalingMsg_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_signalingMsg_specs_13 = {
	sizeof(struct Change__signalingMsg),
	offsetof(struct Change__signalingMsg, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_signalingMsg_13 = {
	"signalingMsg",
	"signalingMsg",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_signalingMsg_tags_13,
	sizeof(asn_DEF_signalingMsg_tags_13)
		/sizeof(asn_DEF_signalingMsg_tags_13[0]) - 1, /* 1 */
	asn_DEF_signalingMsg_tags_13,	/* Same as above */
	sizeof(asn_DEF_signalingMsg_tags_13)
		/sizeof(asn_DEF_signalingMsg_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_signalingMsg_13,
	1,	/* Single element */
	&asn_SPC_signalingMsg_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Change_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Change, caseId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CaseIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caseId"
		},
	{ ATF_POINTER, 1, offsetof(struct Change, iAPSystemId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IAPSystemIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iAPSystemId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Change, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timestamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Change, previous),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_previous_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"previous"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Change, resulting),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_resulting_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resulting"
		},
	{ ATF_POINTER, 2, offsetof(struct Change, protocolSpecificParameters),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProtocolSpecificParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolSpecificParameters"
		},
	{ ATF_POINTER, 1, offsetof(struct Change, signalingMsg),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_signalingMsg_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signalingMsg"
		},
};
static ber_tlv_tag_t asn_DEF_Change_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Change_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* caseId at 116 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* iAPSystemId at 117 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timestamp at 118 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* previous at 120 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* resulting at 122 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* protocolSpecificParameters at 124 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* signalingMsg at 125 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Change_specs_1 = {
	sizeof(struct Change),
	offsetof(struct Change, _asn_ctx),
	asn_MAP_Change_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Change = {
	"Change",
	"Change",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Change_tags_1,
	sizeof(asn_DEF_Change_tags_1)
		/sizeof(asn_DEF_Change_tags_1[0]), /* 1 */
	asn_DEF_Change_tags_1,	/* Same as above */
	sizeof(asn_DEF_Change_tags_1)
		/sizeof(asn_DEF_Change_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Change_1,
	7,	/* Elements count */
	&asn_SPC_Change_specs_1	/* Additional specs */
};

