/*
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -funnamed-unions -findirect-choice -fbless-SIZE -fcompound-names -fnative-types`
 */

#ifndef	_MediaInformation_H_
#define	_MediaInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <UTF8String.h>
#include <OBJECT_IDENTIFIER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MediaInformation__characteristics_PR {
	MediaInformation__characteristics_PR_NOTHING,	/* No components present */
	MediaInformation__characteristics_PR_sdp,
	MediaInformation__characteristics_PR_h323Media,
	MediaInformation__characteristics_PR_other
} MediaInformation__characteristics_PR;
typedef enum MediaInformation__status {
	MediaInformation__status_requested	= 0,
	MediaInformation__status_granted	= 1,
	MediaInformation__status_rejected	= 2,
	MediaInformation__status_relayed	= 3
} e_MediaInformation__status;

/* Forward declarations */
struct BearerCapability;
struct H323Media;

/* MediaInformation */
typedef struct MediaInformation {
	struct BearerCapability	*bearerCapability	/* OPTIONAL */;
	struct MediaInformation__characteristics {
		MediaInformation__characteristics_PR present;
		union {
			UTF8String_t	 sdp;
			struct H323Media	*h323Media;
			struct MediaInformation__characteristics__other {
				OBJECT_IDENTIFIER_t	 type;
				OCTET_STRING_t	 value;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *other;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *characteristics;
	long	*status	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MediaInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_status_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MediaInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BearerCapability.h"
#include "H323Media.h"

#endif	/* _MediaInformation_H_ */
