/*
 * Copyright (c) 2007 Norman Brandinger <norm@goes.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "T1S1-LAES-VoP-Abstract-Syntax-Module"
 * 	found in "T1S1-LAES-VoP-Abstract-Syntax-Module.asn"
 * 	`asn1c -funnamed-unions -findirect-choice -fbless-SIZE -fcompound-names -fnative-types`
 */

#ifndef	_ServingSystem_H_
#define	_ServingSystem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CaseIdentity.h"
#include "IAPSystemIdentity.h"
#include "TimeStamp.h"
#include <VisibleString.h>
#include "AddressRegistrationType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "SipHeader.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_CHOICE.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingSystem__requestAddressInfo_PR {
	ServingSystem__requestAddressInfo_PR_NOTHING,	/* No components present */
	ServingSystem__requestAddressInfo_PR_generic,
	ServingSystem__requestAddressInfo_PR_sip
} ServingSystem__requestAddressInfo_PR;
typedef enum ServingSystem__responseAddressInfo_PR {
	ServingSystem__responseAddressInfo_PR_NOTHING,	/* No components present */
	ServingSystem__responseAddressInfo_PR_generic,
	ServingSystem__responseAddressInfo_PR_sip
} ServingSystem__responseAddressInfo_PR;
typedef enum ServingSystem__expirationPeriod_PR {
	ServingSystem__expirationPeriod_PR_NOTHING,	/* No components present */
	ServingSystem__expirationPeriod_PR_generic,
	ServingSystem__expirationPeriod_PR_sip
} ServingSystem__expirationPeriod_PR;

/* Forward declarations */
struct CallIdentity;
struct PartyIdentity;
struct Cause;
struct ProtocolSpecificParameters;
struct Generic;
struct EncapsulatedSignalingMessage;

/* ServingSystem */
typedef struct ServingSystem {
	CaseIdentity_t	 caseId;
	IAPSystemIdentity_t	*iAPSystemId	/* OPTIONAL */;
	TimeStamp_t	 timestamp;
	VisibleString_t	*systemIdentity	/* OPTIONAL */;
	VisibleString_t	*networkAddress	/* OPTIONAL */;
	struct CallIdentity	*requestId	/* OPTIONAL */;
	AddressRegistrationType_t	*registrationType	/* OPTIONAL */;
	struct PartyIdentity	*registering	/* OPTIONAL */;
	struct PartyIdentity	*requesting	/* OPTIONAL */;
	struct PartyIdentity	*registrar	/* OPTIONAL */;
	struct ServingSystem__requestAddressInfo {
		ServingSystem__requestAddressInfo_PR present;
		union {
			struct ServingSystem__requestAddressInfo__generic {
				A_SEQUENCE_OF(struct Generic) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *generic;
			struct ServingSystem__requestAddressInfo__sip {
				A_SET_OF(SipHeader_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *sip;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *requestAddressInfo;
	struct ServingSystem__responseAddressInfo {
		ServingSystem__responseAddressInfo_PR present;
		union {
			struct ServingSystem__responseAddressInfo__generic {
				A_SEQUENCE_OF(struct Generic) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *generic;
			struct ServingSystem__responseAddressInfo__sip {
				A_SET_OF(SipHeader_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *sip;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *responseAddressInfo;
	struct Cause	*failureReason	/* OPTIONAL */;
	struct ServingSystem__expirationPeriod {
		ServingSystem__expirationPeriod_PR present;
		union {
			long	 generic;
			SipHeader_t	 sip;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *expirationPeriod;
	struct ProtocolSpecificParameters	*protocolSpecificParameters	/* OPTIONAL */;
	struct ServingSystem__signalingMsg {
		A_SET_OF(struct EncapsulatedSignalingMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *signalingMsg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServingSystem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingSystem;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CallIdentity.h"
#include "PartyIdentity.h"
#include "Cause.h"
#include "ProtocolSpecificParameters.h"
#include "Generic.h"
#include "EncapsulatedSignalingMessage.h"

#endif	/* _ServingSystem_H_ */
